Website/Entities/WorkTime.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Website.Entities
{
    public class WorkTime : Entity 
    {
        
        [ForeignKey(nameof(User))]
        public int Id_User { get; set; } = default!;

        [ForeignKey(nameof(Id_User))]
        public User User { get; set; } = default!;

        [DataType(DataType.Date)]
        public DateTime WorkingDay { get; set; } = default!;
        
        public decimal WorkingHours { get; set; } = default!;


    }
}

Website/Controllers/WorkTimesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Website.Database;
using Website.Entities;

namespace Website.Controllers
{
    public class WorkTimesController : Controller
    {
        private readonly AppDbContext _context;

        public WorkTimesController(AppDbContext context)
        {
            _context = context;
        }

        // GET: WorkTimes
        public async Task<IActionResult> Index()
        {
            try
            {
                var appDbContext = _context.WorkTimes.Include(w => w.User);
                var workTimes = await appDbContext.ToListAsync();

                if (workTimes == null)
                {
                    return NotFound(); 
                }

                return View(workTimes);
            }
            catch (Exception ex)
            {
                return View("Home"); 
            }
        }
        public async Task<IActionResult> IndexUser()
        {
            var userId = HttpContext.Session.GetInt32("U_Id");
            var userWorkTimes = await _context.WorkTimes
                .Where(w => w.Id_User == userId)
                .ToListAsync();

            return View(userWorkTimes);
        }

         // GET: WorkTimes/Create for admin and manager 
        public IActionResult Create()
        {
           
            List<User> userList = _context.Users.ToList();

            List<SelectListItem> usersListItems = userList
                .Select(u => new SelectListItem { Value = u.Id.ToString(), Text = $"{u.Name} {u.LastName}" })
                .ToList();

            ViewData["Id_User"] = new SelectList(usersListItems, "Value", "Text");

            return View();
        }
        public IActionResult CreateUser()
        {
            return View();
        }
        //WorkTimes/createUser for user
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateUser(DateTime WorkingDay, decimal WorkingHours)
        {
            try
            {
                if (WorkingDay == default(DateTime) || WorkingHours <= 0)
                {
                    ModelState.AddModelError(string.Empty, "Invalid input parameters.");
                    return View();
                }
                if (WorkingHours > 24)
                {
                    ModelState.AddModelError(string.Empty, "The working day cannot be longer than 24 hours.");
                    return View();
                }

                // Check if the WorkingDay is in the future
                if (WorkingDay > DateTime.Now)
                {
                    ModelState.AddModelError(string.Empty, "Working day cannot be in the future.");
                    return View(); 
                }
                var userId = HttpContext.Session.GetInt32("U_Id");
                var workTime = new WorkTime
                {
                    Id_User = (int)userId,
                    WorkingDay = WorkingDay,
                    WorkingHours = WorkingHours,
                };

                _context.Add(workTime);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(IndexUser));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, "An error occurred while processing your request.");
                return View(); 
            }
        }


        // POST: WorkTimes/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id_User,WorkingDay,WorkingHours")] WorkTime workTime)
        {
            try
            {
                if (workTime.WorkingHours > 24)
                {
                    ModelState.AddModelError(string.Empty, "The working day cannot be longer than 24 hours.");
                    return View();
                }
                _context.Add(workTime);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
               
            }
            catch (Exception ex)
            {
                ViewData["Id_User"] = new SelectList(_context.Users, "Id", "Id", workTime.Id_User);
                return View(workTime); 
            }
        }

        // GET: WorkTimes/Edit/
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.WorkTimes == null)
            {
                return NotFound();
            }

            var workTime = await _context.WorkTimes.FindAsync(id);
            if (workTime == null)
            {
                return NotFound();
            }
            List<User> userList = _context.Users.ToList();

            List<SelectListItem> usersListItems = userList
                .Select(u => new SelectListItem { Value = u.Id.ToString(), Text = $"{u.Name} {u.LastName}" })
                .ToList();

            ViewData["Id_User"] = new SelectList(usersListItems, "Value", "Text");
            return View(workTime);

        }
        public async Task<IActionResult> EditUser(int? id)
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }

                var workTime = await _context.WorkTimes.FindAsync(id);
                if (workTime == null)
                {
                    return NotFound();
                }

                ViewData["Id_User"] = new SelectList(_context.Users, "Id", "Id", workTime.Id_User);
                return View(workTime);
            }
            catch (Exception ex)
            {
                return RedirectToAction(nameof(IndexUser)); 
            }
        }


        // POST: WorkTimes/Edit/
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id_User,WorkingDay,WorkingHours,Id")] WorkTime workTime)
        {
            if (id != workTime.Id)
            {
                return NotFound();
            }
            if (workTime.WorkingHours > 24)
            {
                ModelState.AddModelError(string.Empty, "The working day cannot be longer than 24 hours.");
                return View();
            }

            try
            {
                _context.Update(workTime);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!WorkTimeExists(workTime.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
           
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditUser(int id, [Bind("Id_User,WorkingDay,WorkingHours,Id")] WorkTime workTime)
        {
            if (id != workTime.Id)
            {
                return NotFound();
            }
            if (workTime.WorkingHours > 24)
            {
                ModelState.AddModelError(string.Empty, "The working day cannot be longer than 24 hours.");
                return View();
            }
            if (workTime.WorkingDay > DateTime.Now)
            {
                ModelState.AddModelError(string.Empty, "Working day cannot be in the future.");
                return View(workTime);
            }

            try
            {
                _context.Update(workTime);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!WorkTimeExists(workTime.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(IndexUser));

            
        }

        // GET: WorkTimes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.WorkTimes == null)
            {
                return NotFound();
            }

            var workTime = await _context.WorkTimes
                .Include(w => w.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (workTime == null)
            {
                return NotFound();
            }

            return View(workTime);
        }

        // POST: WorkTimes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                if (_context.WorkTimes == null)
                {
                    return Problem("Entity set 'AppDbContext.WorkTimes' is null.");
                }

                var workTime = await _context.WorkTimes.FindAsync(id);
                if (workTime == null)
                {
                    return NotFound(); 
                }

                _context.WorkTimes.Remove(workTime);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return View("Index"); 
            }
        }

        private bool WorkTimeExists(int id)
        {
          return (_context.WorkTimes?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Website/Views/WorkTimes/Create.cshtml
@model Website.Entities.WorkTime

@{
    ViewData["Title"] = "Create";
}

<div class="main-box p-5 position-absolute top-50 start-50 translate-middle d-flex flex-column">
    <h2 class="mb-5 text-center">Add working hours <br> for employee</h2>
    
    <form asp-action="Create">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group mb-3">
            <label asp-for="Id_User" class="control-label fw-bold mb-3">User:</label>
            <select asp-for="Id_User" class="form-control" asp-items="ViewBag.Id_User"></select>
        </div>

        <div class="form-group mb-3">
            <label asp-for="WorkingDay" class="control-label fw-bold mb-3">Working Day:</label>
            <input asp-for="WorkingDay" class="form-control" type="date" max="@DateTime.Now.ToString("yyyy-MM-dd")" />
        </div>
        
        <div class="form-group">
            <label asp-for="WorkingHours" class="control-label fw-bold mb-3">Working Hours:</label>
            <input asp-for="WorkingHours" type="number" min="0" class="form-control" />
        </div>

        <div class="form-group d-flex mt-4">
            <div class="me-2 fs-3">
                <a asp-action="Index" title="back"><i class="fa-solid fa-circle-left"></i> </a>
            </div>
            <input type="submit" value="Save" class="btn-gradient border-solid flex-fill p-2" />
        </div>
    </form>
</div>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Website/Views/WorkTimes/CreateUser.cshtml
@model Website.Entities.WorkTime
@if (!ViewData.ModelState.IsValid)
{
    <div class="alert alert-danger">
        <ul>
            @foreach (var error in ViewData.ModelState.Values.SelectMany(v => v.Errors))
            {
                <li>@error.ErrorMessage</li>
            }
        </ul>
    </div>
}
@{
    ViewData["Title"] = "CreateUser";
}
<div class="main-box p-5 position-absolute top-50 start-50 translate-middle d-flex flex-column">
    <h2 class="mb-5">Add your working hours</h2>
    @using (Html.BeginForm("CreateUser", "WorkTimes", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
    
        <div class="form-group mb-3">
            <label asp-for="WorkingDay" class="control-label fw-bold mb-3">Working Day:</label>
            <input asp-for="WorkingDay" class="form-control" type="date" max="@DateTime.Now.ToString("yyyy-MM-dd")" />
        </div>
   
        <div class="form-group">
            <label asp-for="WorkingHours" class="control-label fw-bold mb-3">Working Hours:</label>
            <input asp-for="WorkingHours" type="number" min="0"  class="form-control" />
        </div>

        <div class="form-group d-flex mt-4">
            <div class="me-2 fs-3">
                <a asp-action="IndexUser" title="back"><i class="fa-solid fa-circle-left"></i> </a>
            </div>
            <input type="submit" value="Save" class="btn-gradient border-solid flex-fill p-2" />
        </div>
    }
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Website/Views/WorkTimes/Delete.cshtml
@model Website.Entities.WorkTime

@{
    ViewData["Title"] = "Delete";
}

<div class="main-box position-absolute translate-middle top-50 start-50 p-5">
    <h3>Are you sure you want to <strong>delete</strong> this?</h3>    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <div class="form-group d-flex mt-4">
            <div class="me-2 fs-3">
                <a asp-action="Index" title="back"><i class="fa-solid fa-circle-left"></i> </a>
            </div>
            <input type="submit" value="Delete" class="btn-gradient border-solid flex-fill p-2" />
        </div>
    </form>
</div>

Website/Views/WorkTimes/Edit.cshtml
@model Website.Entities.WorkTime

@{
    ViewData["Title"] = "Edit";
}


<div class="main-box p-5 position-absolute top-50 start-50 translate-middle">
    <h1 class="mb-5">Edit work time</h1>
    <form asp-action="Edit">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group mb-4">
            <label asp-for="Id_User" class="control-label fw-bold mb-3">User: </label>
            <select asp-for="Id_User" class="form-control" asp-items="ViewBag.Id_User"></select>
            <span asp-validation-for="Id_User" class="text-danger"></span>
        </div>
            <div class="form-group mb-4">
                <label asp-for="WorkingDay" class="control-label fw-bold mb-3">Working day:</label>
            <input asp-for="WorkingDay" class="form-control" />
            <span asp-validation-for="WorkingDay" class="text-danger"></span>
        </div>
            <div class="form-group mb-4">
                <label asp-for="WorkingHours" class="control-label fw-bold mb-3">Working hours:</label>
                <input asp-for="WorkingHours" type="number" class="form-control" />
                <span asp-validation-for="WorkingHours" class="text-danger"></span>
        </div>
        <input type="hidden" asp-for="Id" />
            <div class="form-group d-flex mt-4">
                <div class="me-2 fs-3">
                    <a asp-action="Index" title="back"><i class="fa-solid fa-circle-left"></i> </a>
                </div>
                <input type="submit" value="Save" class="btn-gradient border-solid flex-fill p-2" />
            </div>
    </form>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Website/Views/WorkTimes/EditUser.cshtml
@model Website.Entities.WorkTime


@{
    ViewData["Title"] = "EditUser";
}
<div class="main-box p-5 position-absolute translate-middle top-50 start-50">
    <h1 class="mb-5">Edit your working hours</h1>
    <form asp-action="EditUser">
        <div asp-validation-summary="ModelOnly" class="text-danger mb-2"></div>
        <div class="form-group" style="display:none;">
            <label asp-for="Id_User" class="control-label mb-2 fw-bold">User:</label>
            <select asp-for="Id_User" class="form-control" asp-items="ViewBag.Id_User"></select>
            <span asp-validation-for="Id_User" class="text-danger"></span>
        </div>
        <div class="form-group mb-3">
            <label asp-for="WorkingDay" class="control-label fw-bold mb-2">Working day:</label>
            <input asp-for="WorkingDay" class="form-control" type="date" max="@DateTime.Now.ToString("yyyy-MM-dd")" />
        </div>
        <div class="form-group mb-3">
            <label asp-for="WorkingHours" class="control-label mb-2 fw-bold">Working hours:</label>
            <input asp-for="WorkingHours" type="number" step="0.50" class="form-control" />
            <span asp-validation-for="WorkingHours" class="text-danger"></span>
        </div>
        <input type="hidden" asp-for="Id" />
        <div class="form-group d-flex mt-4">
            <div class="me-2 fs-3">
                <a asp-action="IndexUser" title="back"><i class="fa-solid fa-circle-left"></i> </a>
            </div>
            <input type="submit" value="Save" class="btn-gradient border-solid flex-fill p-2" />
        </div>
    </form>

</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Website/Views/WorkTimes/Index.cshtml
@model IEnumerable<Website.Entities.WorkTime>

@{
    ViewData["Title"] = "Index";
}
<link rel="stylesheet" href="~/css/table.css" />

<div class="main-box p-3 mb-3">
    <div class="d-flex justify-content-between flex-wrap">
        <h1>Working hours</h1>
        <p><a asp-action="Create" class="btn-gradient border-solid nav-link mt-1">Create New</a></p>
    </div>
</div>
<div class="main-box p-3">
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.User)
                </th>
                <th>
                   Day
                </th>
                <th>
                   Hours
                </th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.User.Name)
                        @Html.DisplayFor(modelItem => item.User.LastName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.WorkingDay)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.WorkingHours)
                    </td>
                    <td>
                        <div class="d-flex flex-wrap justify-content-end">
                            <a asp-action="Edit" class="btn btn-outline-success me-1" asp-route-id="@item.Id"><i class="fas fa-edit"></i> Edit</a>
                            <a asp-action="Delete" class="btn btn-outline-danger" asp-route-id="@item.Id"><i class="fas fa-trash"></i> Delete</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

Website/Views/WorkTimes/IndexUser.cshtml
@model IEnumerable<Website.Entities.WorkTime>

@{
    ViewData["Title"] = "Index";
}
<link rel="stylesheet" href="~/css/table.css" />

<div class="main-box p-3 d-flex justify-content-between">
    <h1>Your working hours</h1>
    <p><a asp-action="CreateUser" class="btn-gradient border-solid nav-link mt-1">Create New</a></p>
</div>
<div class="main-box p-3 mt-3">
    <table class="table">
        <thead>
            <tr>
                <th>
                    <p>Day</p>
                </th>
                <th>
                    <p>Hours</p>
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
    @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.WorkingDay)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.WorkingHours)
                </td>
                <td>
                    <div class="button-container text-end">
                       <a asp-action="EditUser" class="btn btn-outline-success" asp-route-id="@item.Id"><i class="fas fa-edit"></i>Edit</a>
                    </div>
                </td>
            </tr>
    }
        </tbody>
    </table>
</div>