Website/Controllers/ApproveController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Website.Database;
using Website.Entities;
using Website.Models;

namespace Website.Controllers
{
    public class ApproveController : Controller
    {
        private readonly AppDbContext _context;

        public ApproveController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var userId = HttpContext.Session.GetInt32("U_Id");
            var roleName = HttpContext.Session.GetString("R_Name");

            try
            {
                
                    var query = from user in _context.Users
                                join employment in _context.Employments on user.Id equals employment.Id_User
                                join application in _context.Applications on user.Id equals application.Id_User
                                join category in _context.Categories on application.Id_Category equals category.Id
                                where employment.Id_Manager == userId
                                where application.Id_Category == 1
                                select new Approve
                                {
                                    User = user,
                                    Employment = employment,
                                    Application = application,
                                    Category = category
                                };
                    var result = query.ToList();


                    return View(result);

       

            }
            catch (Exception ex)
            {
                return View("Home"); 
            }
        }


        public ActionResult Accept(int id)
        {
            try
            {
                var recordToEdit = _context.Applications.Find(id);

                if (recordToEdit == null)
                {
                    return NotFound();
                }

                recordToEdit.Id_Category = 3;
                recordToEdit.ChangeCatDate = DateTime.Now;


                _context.SaveChanges();

                return RedirectToAction("Archives");
            }
            catch (Exception ex)
            {

                return View("Index"); 
            }
        }

        public ActionResult Reject(int id)
        {
            try
            {
                var recordToEdit = _context.Applications.Find(id);

                if (recordToEdit == null)
                {
                    return NotFound();
                }

                recordToEdit.Id_Category = 2;
                recordToEdit.ChangeCatDate = DateTime.Now;

                _context.SaveChanges();

                return RedirectToAction("Archives");
            }
            catch (Exception ex)
            {
                return View("Index");
            }
        }

        public IActionResult Archives()
        {
            var userId = HttpContext.Session.GetInt32("U_Id");
            var roleName = HttpContext.Session.GetString("R_Name");

            try
            {
                if (roleName == "Manager")
                {
                    var query = from user in _context.Users
                                join employment in _context.Employments on user.Id equals employment.Id_User
                                join application in _context.Applications on user.Id equals application.Id_User
                                join category in _context.Categories on application.Id_Category equals category.Id
                                where employment.Id_Manager == userId
                                where application.Id_Category != 1
                                select new Approve
                                {
                                    User = user,
                                    Employment = employment,
                                    Application = application,
                                    Category = category
                                };
                    var sortedQuery = query.OrderByDescending(approve => approve.Application.ChangeCatDate);

                    var result = sortedQuery.ToList();
                    return View(result);


                }
                if (roleName == "Admin")
                {
                    var query = from user in _context.Users
                                join employment in _context.Employments on user.Id equals employment.Id_User
                                join application in _context.Applications on user.Id equals application.Id_User
                                join category in _context.Categories on application.Id_Category equals category.Id
                                where application.Id_Category != 1
                                select new Approve
                                {
                                    User = user,
                                    Employment = employment,
                                    Application = application,
                                    Category = category
                                };
                    var sortedQuery = query.OrderByDescending(approve => approve.Application.ChangeCatDate);

                    var result = sortedQuery.ToList();
                    return View(result);

                }
                else
                {
                    return View("Home");
                }

            }

            catch (Exception ex)
            {
                return View("Home");
            }


        }
        public IActionResult AllApplications()
        {
            try
            {
                var query = from user in _context.Users
                            join employment in _context.Employments on user.Id equals employment.Id_User
                            join application in _context.Applications on user.Id equals application.Id_User
                            join category in _context.Categories on application.Id_Category equals category.Id
                            where application.Id_Category == 1
                            select new Approve
                            {
                                User = user,
                                Employment = employment,
                                Application = application,
                                Category = category
                            };


                var result = query.ToList();

                return View(result);
            }

            catch (Exception ex)
            {
                return View("Home");
            }


        }

    }
}

Website/Controllers/UserController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Win32;
using NuGet.Protocol.Plugins;
using System.Data;
using System.Text.RegularExpressions;
using Website.Database;
using Website.Entities;
using Website.Models;
using Website.Models.Account;
using Website.Service;
using Website.Service.AccountService;

namespace Website.Controllers
{
    public class UserController : Controller
    {
        private AppDbContext _context;

        public UserController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index(string searchName = null, string searchLastname = null)
        {

            try
            {
                List<Tuple<User, LoginData, Role>> usersWithLoginDataAndRole;

                if (!string.IsNullOrEmpty(searchName) && !string.IsNullOrEmpty(searchLastname))
                {
                    usersWithLoginDataAndRole = FindUser(searchName, searchLastname);
                }
                else
                {
                    usersWithLoginDataAndRole = GetUsersWithLoginDataAndRole();
                }

                return View(usersWithLoginDataAndRole);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
                ErrorViewModel errorModel = new ErrorViewModel { ErrorMessage = $"Error: {ex.Message}" };
                return View("Error", errorModel);

            }
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(Register register)
        {
            try
            {
                User user = new User
                {
                    Name = register.User.Name,
                    LastName = register.User.LastName,
                    Email = register.User.Email
                };

                Role role = _context.Roles.SingleOrDefault(i => i.Id == 3 && i.Name == "Employee");

                if (role == null)
                {
                    ModelState.AddModelError(string.Empty, "The Employee role does not exist in the database.");
                    return View("Create", register);
                }

                LoginData loginData = new LoginData
                (
                    register.LoginData.Login,
                    register.LoginData.Password,
                    user.Id,
                    user,
                    role.Id,
                    role
                );

                _context.Users.Add(user);
                _context.LoginData.Add(loginData);
                _context.SaveChanges();
                _context.Dispose();
                TempData["UserId"] = user.Id;
                return RedirectToAction("Create", "Employment");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
                ErrorViewModel errorModel = new ErrorViewModel { ErrorMessage = $"Error: {ex.Message}" };
                return View("Error", errorModel);
            }
        }

        public IActionResult Edit(int Id)
        {
            try
            {
                User editUser = _context.Users.FirstOrDefault(i => i.Id == Id);
                
                bool hasRoleOne = _context.LoginData.Any(ld => ld.Id_User == editUser.Id && ld.Id_Role == 1);

                if (hasRoleOne)
                {
                    ModelState.AddModelError(string.Empty, "Cannot edit a user with the admin role.");
                    List<Tuple<User, LoginData, Role>> usersWithLoginDataAndRole = GetUsersWithLoginDataAndRole();
                    return View("Index", usersWithLoginDataAndRole);
                }

                _context.Dispose();
                return View(editUser);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
                ErrorViewModel errorModel = new ErrorViewModel { ErrorMessage = $"Error: {ex.Message}" };
                return View("Error", errorModel);
            }

        }

        public IActionResult Save(User user)
        {
            try
            {
                User editUser = _context.Users.FirstOrDefault(i => i.Id == user.Id);

                editUser.Name = user.Name;
                editUser.LastName = user.LastName;
                editUser.Email = user.Email;

                _context.SaveChanges();
                _context.Dispose();
                return Redirect("Index");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
                ErrorViewModel errorModel = new ErrorViewModel { ErrorMessage = $"Error: {ex.Message}" };
                return View("Error", errorModel);
            }
        }

        public IActionResult Details(int Id)
        {
            try
            {
                User detailsUser = _context.Users.FirstOrDefault(i => i.Id == Id);
                LoginData loginData = _context.LoginData.FirstOrDefault(ld => ld.Id_User == Id);

                Tuple<User, LoginData> userDetails = new Tuple<User, LoginData>(detailsUser, loginData);
                
                bool hasRoleOne = _context.LoginData.Any(ld => ld.Id_User == detailsUser.Id && loginData.Id_Role == 1);

                if (hasRoleOne)
                {
                    ModelState.AddModelError(string.Empty, "Cannot view details a user with the admin role.");
                    List<Tuple<User, LoginData, Role>> usersWithLoginDataAndRole = GetUsersWithLoginDataAndRole();
                    return View("Index", usersWithLoginDataAndRole);
                }
                _context.Dispose();
                return View(userDetails);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
                ErrorViewModel errorModel = new ErrorViewModel { ErrorMessage = $"Error: {ex.Message}" };
                return View("Error", errorModel);
            }
        }

        public IActionResult Delete(int Id)
        {
            try
            {
                User deleteUser = _context.Users.FirstOrDefault(i => i.Id == Id);

                bool hasRoleOne = _context.LoginData.Any(ld => ld.Id_User == deleteUser.Id && ld.Id_Role == 1);

                if (hasRoleOne)
                {
                    ModelState.AddModelError(string.Empty, "Cannot delete a user with the admin role.");
                    List<Tuple<User, LoginData, Role>> usersWithLoginDataAndRole = GetUsersWithLoginDataAndRole();
                    return View("Index", usersWithLoginDataAndRole);
                }

                bool isManager = _context.Employments.Any(e => e.Id_Manager == deleteUser.Id);

                if (isManager)
                {
                    ModelState.AddModelError(string.Empty, "Cannot delete a user who has a subordinate.");
                    List<Tuple<User, LoginData, Role>> usersWithLoginDataAndRole = GetUsersWithLoginDataAndRole();
                    return View("Index", usersWithLoginDataAndRole);
                }

                _context.Dispose();
                return View(deleteUser);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
                ErrorViewModel errorModel = new ErrorViewModel { ErrorMessage = $"Error: {ex.Message}" };
                return View("Error", errorModel);
            }
        }

        public IActionResult Remove(User user)
        {
            try
            {
                User deleteUser = _context.Users.FirstOrDefault(i => i.Id == user.Id);
                LoginData loginData = _context.LoginData.FirstOrDefault(i => i.Id_User == user.Id);
                List<Employment> employments = _context.Employments
                    .Where(e => e.Id_User == user.Id)
                    .ToList();
                
                if (deleteUser != null && loginData != null && employments != null)
                {
                    _context.Users.Remove(deleteUser);
                    _context.LoginData.Remove(loginData);
                    _context.Employments.RemoveRange(employments);
                    _context.SaveChanges();
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Something has gone wrong.");
                    return View(user);
                }

                _context.Dispose();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
                ErrorViewModel errorModel = new ErrorViewModel { ErrorMessage = $"Error: {ex.Message}" };
                return View("Error", errorModel);
            }
        }
        public IActionResult ChangeLogin(int Id)
        {
            try
            {
                LoginData editLoginData = _context.LoginData.FirstOrDefault(i => i.Id_User == Id);
                editLoginData.Password = string.Empty;

                if (editLoginData.Id_Role == 1)
                {
                    ModelState.AddModelError(string.Empty, "Cannot change the login data of an administrator.");
                    List<Tuple<User, LoginData, Role>> usersWithLoginDataAndRole = GetUsersWithLoginDataAndRole();
                    return View("Index", usersWithLoginDataAndRole);
                }

                return View(editLoginData);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
                ErrorViewModel errorModel = new ErrorViewModel { ErrorMessage = $"Error: {ex.Message}" };
                return View("Error", errorModel);
            }
        }

        public IActionResult SaveLogin(LoginData loginData)

Website/Views/Shared/MenuTypes/_admin.cshtml
<li class="btn-gradient mb-2">
    <a class="nav-link text-dark" asp-controller="User" asp-action="Index">Users</a>
</li>
<li class="btn-gradient mb-2">
    <a class="nav-link text-dark" asp-controller="Employment" asp-action="Index">Employments</a>
</li>
<li class="btn-gradient mb-2">
    <a class="nav-link text-dark" asp-controller="Positions" asp-action="Index">Positions</a>
</li>
<li class="btn-gradient mb-2">
    <a class="nav-link text-dark" asp-controller="Report" asp-action="Index">Reports</a>
</li>
<li data-bs-toggle="collapse" data-bs-target="#flush-worktime" aria-expanded="false" class="btn-gradient mb-2">
        <a class="nav-link text-dark">Work Time <i class="fa-solid fa-chevron-down"></i></a>
</li>
<ul id="flush-worktime" class="collapse">
    <li class="btn-gradient mb-2"><a class="nav-link text-dark" asp-controller="WorkTimes" asp-action="CreateUser">Add new</a></li>
    <li class="btn-gradient mb-2"><a class="nav-link text-dark" asp-controller="WorkTimes" asp-action="IndexUser">Your time</a></li>
    <li class="btn-gradient mb-2"><a class="nav-link text-dark" asp-controller="WorkTimes" asp-action="Create">Add employee time</a></li>
    <li class="btn-gradient mb-2"><a class="nav-link text-dark" asp-controller="WorkTimes" asp-action="Index">Archives</a></li>
</ul>

<li data-bs-toggle="collapse" data-bs-target="#flush-app" aria-expanded="false" class="btn-gradient mb-2">
    <a class="nav-link text-dark">Applications <i class="fa-solid fa-chevron-down"></i> </a>
</li>
<ul id="flush-app" class="collapse">
    <li class="btn-gradient mb-2"><a class="nav-link text-dark" asp-controller="Applications" asp-action="Create">Add new</a></li>
    <li class="btn-gradient mb-2"><a class="nav-link text-dark" asp-controller="Approve" asp-action="AllApplications">All applications</a></li>
    <li class="btn-gradient mb-2"><a class="nav-link text-dark" asp-controller="Applications" asp-action="Index">Your application</a></li>
    <li class="btn-gradient mb-2"><a class="nav-link text-dark" asp-controller="Categories" asp-action="Index">Categories</a></li>
    <li class="btn-gradient mb-2"><a class="nav-link text-dark" asp-controller="Approve" asp-action="Archives">Archives</a></li>
</ul>

Website/Views/Shared/MenuTypes/_employee.cshtml
<li class="btn-gradient mb-2">
    <a class="nav-link text-dark" asp-controller="Applications" asp-action="Index">Application</a>
</li>

<li data-bs-toggle="collapse" data-bs-target="#flush-worktime" aria-expanded="false" class="btn-gradient mb-2">
    <a class="nav-link text-dark">Work Time <i class="fa-solid fa-chevron-down"></i></a>
</li>
<ul id="flush-worktime" class="collapse">
    <li class="btn-gradient mb-2"><a class="nav-link text-dark" asp-controller="WorkTimes" asp-action="CreateUser">Add new</a></li>
    <li class="btn-gradient mb-2"><a class="nav-link text-dark" asp-controller="WorkTimes" asp-action="IndexUser">History</a></li>
</ul>

Website/Views/Shared/MenuTypes/_manager.cshtml
<li class="btn-gradient mb-2">
    <a class="nav-link text-dark" asp-controller="User" asp-action="Index">Users</a>
</li>
<li class="btn-gradient mb-2">
    <a class="nav-link text-dark" asp-controller="Employment" asp-action="Index">Employments</a>
</li>

<li class="btn-gradient mb-2">
    <a class="nav-link text-dark" asp-controller="Report" asp-action="Index">Reports</a>
</li>
<li class="btn-gradient mb-2">
    <a class="nav-link text-dark" asp-controller="Calendar" asp-action="Index">Holiday statistics</a>
</li>

<li data-bs-toggle="collapse" data-bs-target="#flush-worktime" aria-expanded="false" class="btn-gradient mb-2">
    <a class="nav-link text-dark">Work Time <i class="fa-solid fa-chevron-down"></i></a>
</li>
<ul id="flush-worktime" class="collapse">
    <li class="btn-gradient mb-2"><a class="nav-link text-dark" asp-controller="WorkTimes" asp-action="IndexUser">Your History</a></li>
    <li class="btn-gradient mb-2"><a class="nav-link text-dark" asp-controller="WorkTimes" asp-action="Create">Add employee time</a></li>
    <li class="btn-gradient mb-2"><a class="nav-link text-dark" asp-controller="WorkTimes" asp-action="CreateUser">Add new</a></li>
    <li class="btn-gradient mb-2"><a class="nav-link text-dark" asp-controller="WorkTimes" asp-action="Index">History</a></li>
</ul>

<li data-bs-toggle="collapse" data-bs-target="#flush-app" aria-expanded="false" class="btn-gradient mb-2">
    <a class="nav-link text-dark">Applications <i class="fa-solid fa-chevron-down"></i> </a>
</li>
<ul id="flush-app" class="collapse">
    <li class="btn-gradient mb-2"><a class="nav-link text-dark" asp-controller="Applications" asp-action="Create">Add</a></li>
    <li class="btn-gradient mb-2"><a class="nav-link text-dark" asp-controller="Applications" asp-action="Index">List</a></li>
    <li class="btn-gradient mb-2"><a class="nav-link text-dark" asp-controller="Approve" asp-action="Index">To accept</a></li>
    <li class="btn-gradient mb-2"><a class="nav-link text-dark" asp-controller="Approve" asp-action="Archives">Archives</a></li>

</ul>
<li class="nav-item btn-gradient mb-2">
    <a class="nav-link text-dark" asp-area="" asp-controller="WorkTimes" asp-action="Index"> Time Entry</a>
</li>