Website/Entities/Employment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Website.Entities
{
    public class Employment: Entity
    {
        public DateTime EmploymentDate { get; set; } = default!;
        
        public decimal Rate { get; set; } = default!;


        [ForeignKey(nameof(User))]
        public int Id_User { get; set; } = default!;

        [ForeignKey(nameof(Id_User))]
        public User User { get; set; } = default!;

        [ForeignKey(nameof(Manager))]
        public int? Id_Manager { get; set; }

        [ForeignKey(nameof(Id_Manager))]
        public User? Manager { get; set; }

        [ForeignKey(nameof(Id_Position))]
        public int Id_Position { get; set; } = default!;
        
        [ForeignKey(nameof(Id_Position))]
        public Position Position { get; set; } = default!;
    }
}

Website/Controllers/EmploymentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using Website.Database;
using Website.Entities;
using Website.Models;
using Website.Models.Account;
using Microsoft.CodeAnalysis.Elfie.Diagnostics;
using NuGet.DependencyResolver;
using static System.Runtime.InteropServices.JavaScript.JSType;
using Position = Website.Entities.Position;
using Microsoft.Win32;

namespace Website.Controllers
{
    public class EmploymentController : Controller
    {
        private AppDbContext _context;

        public EmploymentController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            try
            {
                List<Employment> employments = _context.Employments
                    .Include(e => e.User)
                    .Include(e => e.Manager)
                    .Include(e => e.Position)
                    .ToList();

                return View(employments);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
                ErrorViewModel errorModel = new ErrorViewModel { ErrorMessage = $"Error: {ex.Message}" };
                return View("Error", errorModel);
            }
        }

        public IActionResult Create()
        {
            List<User> userList = _context.Users
                    .Join(
                        _context.LoginData,
                        user => user.Id,
                        login => login.Id_User,
                        (user, login) => new { User = user, Login = login }
                        )
                    .Where(joinResult => joinResult.Login.Id_Role == 2)
                    .Select(u => new User { Id = u.User.Id, Name = u.User.Name, LastName = u.User.LastName })
                    .ToList();

            List<SelectListItem> usersListItems = userList
                    .Select(u => new SelectListItem { Value = u.Id.ToString(), Text = $"{u.Name} {u.LastName}" })
                    .ToList();

            usersListItems.Insert(0, new SelectListItem { Value = "", Text = "-- No manager --" });

            ViewData["Id_User"] = new SelectList(usersListItems, "Value", "Text");

            List<Position> positionList = _context.Positions.ToList();

            List<SelectListItem> positionsListItems = positionList
                    .Select(p => new SelectListItem { Value = p.Id.ToString(), Text = $"{p.Name}" })
                    .ToList();

            ViewData["Id_Position"] = new SelectList(positionsListItems, "Value", "Text");

            return View();
        }

        [HttpPost]
        public IActionResult Add(Employment employment)
        {
            try
            {
                int userId = (int)TempData["UserId"];
                User user = _context.Users.FirstOrDefault(i => i.Id == userId);
                User manager = _context.Users.FirstOrDefault(u => u.Id == employment.Id_Manager);
                Position position = _context.Positions.FirstOrDefault(p => p.Id == employment.Id_Position);

                employment.User = user;
                employment.Id_User = user.Id;
                employment.Manager = manager;
                employment.Position = position;
                employment.Id_Position = position.Id;

                if (manager != null)
                {
                    employment.Id_Manager = manager.Id;
                }
                else
                {
                    employment.Id_Manager = null;
                }

                _context.Employments.Add(employment);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
                ErrorViewModel errorModel = new ErrorViewModel { ErrorMessage = $"Error: {ex.Message}" };
                return View("Error", errorModel);
            }
            finally
            {
                _context.Dispose();
            }
        }

        public IActionResult Edit(int Id)
        {
            try
            {
                List<User> userList = _context.Users
                    .Join(
                        _context.LoginData,
                        user => user.Id,
                        login => login.Id_User,
                        (user, login) => new { User = user, Login = login }
                        )
                    .Where(joinResult => joinResult.Login.Id_Role == 2)
                    .Select(u => new User { Id = u.User.Id, Name = u.User.Name, LastName = u.User.LastName })
                    .ToList();

                List<SelectListItem> usersListItems = userList
                    .Select(u => new SelectListItem { Value = u.Id.ToString(), Text = $"{u.Name} {u.LastName}" })
                    .ToList();

                usersListItems.Insert(0, new SelectListItem { Value = "", Text = "-- No manager --" });

                ViewData["Id_User"] = new SelectList(usersListItems, "Value", "Text");

                List<Position> positionList = _context.Positions.ToList();

                List<SelectListItem> positionsListItems = positionList
                    .Select(p => new SelectListItem { Value = p.Id.ToString(), Text = $"{p.Name}" })
                    .ToList();

                ViewData["Id_Position"] = new SelectList(positionsListItems, "Value", "Text");

                Employment editEmployment = _context.Employments
                    .Include(e => e.User)
                    .Include(e => e.Manager)
                    .Include(e => e.Position)
                    .FirstOrDefault(e => e.Id == Id);
                
                editEmployment.Rate = Math.Round(editEmployment.Rate, 1);
                return View(editEmployment);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
                ErrorViewModel errorModel = new ErrorViewModel { ErrorMessage = $"Error: {ex.Message}" };
                return View("Error", errorModel);
            }
        }

        [HttpPost]
        public IActionResult Save(Employment employment)
        {
            try
            {
                Employment editEmployment = _context.Employments
                    .Include(e => e.User)
                    .Include(e => e.Manager)
                    .Include(e => e.Position)
                    .FirstOrDefault(e => e.Id == employment.Id);

                User user = _context.Users.FirstOrDefault(i => i.Name == employment.User.Name && i.LastName == employment.User.LastName);
                User manager = _context.Users.FirstOrDefault(u => u.Id == employment.Id_Manager);
                Position position = _context.Positions.FirstOrDefault(p => p.Id == employment.Id_Position);

                editEmployment.EmploymentDate = employment.EmploymentDate;
                editEmployment.User = user;
                editEmployment.Id_User = user.Id;
                editEmployment.Manager = manager;
                editEmployment.Position = position;
                editEmployment.Id_Position = position.Id;
                editEmployment.Rate = employment.Rate;

                if (manager != null)
                {
                    editEmployment.Id_Manager = manager.Id;
                }
                else
                {
                    editEmployment.Id_Manager = null;
                }

                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
                ErrorViewModel errorModel = new ErrorViewModel { ErrorMessage = $"Error: {ex.Message}" };
                return View("Error", errorModel);
            }
            finally
            {
                _context.Dispose();
            }
        }
        public IActionResult GroupAction()
        {
            return View();
        }

        public IActionResult MakeGroupAction(Employment emp)
        {
            if(emp.Rate == 0)
            {
                ModelState.AddModelError(string.Empty, "The Increase/Decrease value cannot be 0.");
                return View("GroupAction");
            }

            List<Employment> employments = _context.Employments
                    .Include(e => e.User)
                    .Include(e => e.Manager)
                    .Include(e => e.Position)
                    .ToList(); 
            
            foreach (Employment employment in employments)
            {
                employment.Rate += emp.Rate;
                
                if (employment.Rate < 0)
                {
                    employment.Rate = 0;
                }
            }

            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Details(int Id)
        {
            try
            {
                Employment employment = _context.Employments
                    .Include(e => e.User)
                    .Include(e => e.Manager)
                    .Include(e => e.Position)
                    .FirstOrDefault(e => e.Id == Id);

                return View(employment);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
                ErrorViewModel errorModel = new ErrorViewModel { ErrorMessage = $"Error: {ex.Message}" };
                return View("Error", errorModel);
            }
            finally
            {
                _context.Dispose();
            }
        }
    }
}

Website/Views/Employment/Create.cshtml
@model Website.Entities.Employment

@{
    ViewData["Title"] = "Create";
}

<div class="main-box position-absolute top-50 start-50 translate-middle p-5">


    <h1 class="mb-4">Create employment</h1>

    @using (Html.BeginForm("Add", "Employment", FormMethod.Post))
    {
        <form asp-action="Create" method="post">
            <div class="form-group mb-3">
                <label class="control-label fw-bold mb-3">Manager</label>
                <select asp-for="Id_Manager" class="form-control" asp-items="ViewBag.Id_User"></select>
            </div>

            <div class="form-group mb-3">
                <label asp-for="EmploymentDate" class="control-label fw-bold mb-3">Employment Date</label>
                <input asp-for="EmploymentDate" type="date" class="form-control" max="@DateTime.Now.ToString("yyyy-MM-dd")" required />
            </div>

            <div class="form-group mb-3">
                <label asp-for="Rate" class="control-label fw-bold mb-3">Rate</label>
                <input asp-for="Rate" type="number" step="0.50" class="form-control" min="0.50" max="100" required />
            </div>

            <div class="form-group mb-3">
                <label class="control-label fw-bold mb-3">Position</label>
                <select asp-for="Id_Position" class="form-control" asp-items="ViewBag.Id_Position"></select>
            </div>

            <div class="form-group d-flex mt-4">
                <div class="me-2 fs-3">
                    <a asp-action="Index" title="back"><i class="fa-solid fa-circle-left"></i> </a>
                </div>
                <input type="submit" value="Create" class="btn-gradient border-solid flex-fill p-2 text-center">
            </div>
        </form>
    }
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Website/Views/Employment/Details.cshtml
@model Website.Entities.Employment

@{
    ViewData["Title"] = "Details";
    string formattedDate = Model.EmploymentDate.ToShortDateString();
}

<div class="position-absolute top-50 start-50 translate-middle main-box p-5">
    <h1 class="mb-3">Details employment</h1>
    
    <div class="d-flex justify-content-center">
        <div class="flex-fill me-5">
            <div class="mb-3 d-flex flex-column">
                <p>@Html.DisplayNameFor(model => model.User)</p>
                <input value="@Html.DisplayFor(model => model.User.Name) @Html.DisplayFor(model => model.User.LastName)" class="p-1" readonly />
            </div>
            <div class="mb-3">
                <p> @Html.DisplayNameFor(model => model.Manager)</p>
                <input value="@Html.DisplayNameFor(model => model.Manager) @Html.DisplayFor(model => model.Manager.LastName)" class="p-1" readonly />
            </div>
            <div class="mb-3">
                <p>Employment date</p>
                <input value="@formattedDate" class="p-1" readonly />
            </div>
        </div>
        <div class="flex-fill">
            <div class="mb-3">
                <p>@Html.DisplayNameFor(model => model.Rate)</p>
                <input value="@Html.DisplayFor(model => model.Rate)" class="p-1" readonly />
            </div>
            <div class="mb-3"
            >
                <p>@Html.DisplayNameFor(model => model.Position)</p>
                <input value="@Html.DisplayFor(model => model.Position.Name)" class="p-1" readonly />
            </div>
        </div>
    </div>
    <div class="form-group d-flex mt-4">
        <div class="me-2 fs-3">
            <a asp-action="Index" title="back"><i class="fa-solid fa-circle-left"></i> </a>
        </div>
            <a asp-action="Edit" class="btn-gradient border-solid flex-fill p-2 text-center" asp-route-id="@Model?.Id">Edit</a>
    </div>
</div>

Website/Views/Employment/Edit.cshtml
@model Website.Entities.Employment

@{
    ViewData["Title"] = "Edit";
}
<div class="position-absolute top-50 start-50 translate-middle main-box p-5">
<h1 class="text-center mb-5">Edit employment</h1>
        <div>
            @using (Html.BeginForm("Save", "Employment", FormMethod.Post))
            {
            <form asp-action="Edit">
                <div class="d-flex justify-content-center">

                    <div class="flex-fill me-5">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group mb-3">
                            <label asp-for="User.Name" class="control-label mb-3"></label>
                            <input asp-for="User.Name" class="form-control" readonly />
                            <span asp-validation-for="User.Name" class="text-danger mw-350"></span>
                        </div>
                        <div class="form-group mb-3">
                            <label asp-for="User.LastName" class="control-label mb-3"></label>
                            <input asp-for="User.LastName" class="form-control" readonly />
                            <span asp-validation-for="User.LastName" class="text-danger mw-350"></span>
                        </div>
                        <div class="form-group mb-3">
                            <label class="control-label mb-3">Manager</label>
                            <select asp-for="Id_Manager" class="form-control mb-3" asp-items="ViewBag.Id_User"></select>
                        </div>
                    </div>
                    <div class="flex-fill">
                        <div class="form-group mb-3">
                            <label asp-for="EmploymentDate" class="control-label mb-3">Employment date</label>
                            <input asp-for="EmploymentDate" type="date" class="form-control" max="@DateTime.Now.ToString("yyyy-MM-dd")" required />
                            <span asp-validation-for="EmploymentDate" class="text-danger mw-350"></span>
                        </div>
                        <div class="form-group mb-3">
                            <label asp-for="Rate" class="control-label mb-3"></label>
                            <input asp-for="Rate" type="number" step="0.50" class="form-control" min="0.50" max="100" required />
                            <span asp-validation-for="Rate" class="text-danger mw-350"></span>
                        </div>
                        <div class="form-group mb-3">
                            <label class="control-label mb-3">Position</label>
                            <select asp-for="Id_Position" class="form-control" asp-items="ViewBag.Id_Position"></select>
                        </div>
                    </div>
                </div>
                    <input type="hidden" asp-for="Id" />
                    <div class="form-group d-flex mt-4">
                        <div class="me-2 fs-3">
                            <a asp-action="Index" title="back"><i class="fa-solid fa-circle-left"></i> </a>
                        </div>
                        <input type="submit" value="Save" class="btn-gradient border-solid flex-fill p-2" />
                    </div>
                </form>
            }
        </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Website/Views/Employment/GroupAction.cshtml
@model Website.Entities.Employment

@{
    ViewData["Title"] = "GroupAction";
}

<div class="position-absolute top-50 start-50 translate-middle main-box p-5">
    <div class="text-center mb-5 mt-5">
        <h1 class="mb-3">Group Action</h1>
        <h4 class="">Rate Increase/Decrease</h4>
    </div>
    
    <div class="row">
        <div class="">
            @using (Html.BeginForm("MakeGroupAction", "Employment", FormMethod.Post))
            {
                <form asp-action="GroupAction">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group mb-2">
                        <label asp-for="Rate" class="control-label fw-bold mb-2">Value</label>
                        <input asp-for="Rate" class="form-control" type="number" step="0.50" min="-100" max="100" required/>
                        <span asp-validation-for="Rate" class="text-danger  mw-350"></span>
                    </div>
                    <div class="form-group d-flex mt-4">
                        <div class="me-2 fs-3">
                            <a asp-action="Index" title="back"><i class="fa-solid fa-circle-left"></i> </a>
                        </div>
                        <input type="submit" value="Make action" class="btn-gradient flex-fill p-2" />
                    </div>
                </form>
            }
        </div>
    </div>
</div>    

Website/Views/Employment/Index.cshtml
@model IEnumerable<Website.Entities.Employment>

@{
    ViewData["Title"] = "Employments";
}

<link rel="stylesheet" href="~/css/table.css" />

<div class="d-flex justify-content-between main-box p-3 mb-3">
    <h1>Employments</h1>
    <a asp-action="GroupAction" class="btn-gradient nav-link pt-3">Rate Increase/Decrease</a>
</div>

<div class="main-box p-4 main-box-table">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col" class="bg-light">
                            Employment date
                        </th>

                        <th scope="col" class="">
                            @Html.DisplayNameFor(model => model.User)
                        </th>
                        <th scope="col" class="bg-light">
                            @Html.DisplayNameFor(model => model.Manager)
                        </th>
                        <th scope="col">
                            @Html.DisplayNameFor(model => model.Position)
                        </th>
                        <th scope="col" class="bg-light">
                            @Html.DisplayNameFor(model => model.Rate)
                        </th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td class="bg-light">
                                @{
                                    string formattedDate = item.EmploymentDate.ToShortDateString();
                                }
                                @formattedDate
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => item.User.Name)
                                @Html.DisplayFor(modelItem => item.User.LastName)
                            </td>
                            <td class="bg-light">
                                @Html.DisplayFor(modelItem => item.Manager.Name)
                                @Html.DisplayFor(modelItem => item.Manager.LastName)
                            </td>
                            <td >
                                @Html.DisplayFor(modelItem => item.Position.Name)
                            </td>
                            <td class="bg-light">
                                    @Html.DisplayFor(modelItem => item.Rate)
                            </td>
                            <td>
                                <div class="d-flex flex-wrap">
                                    <a asp-action="Details" class="btn btn-outline-primary me-2" asp-route-id="@item.Id"><i class="far fa-eye"></i> Details</a>
                                    <a asp-action="Edit" class="btn btn-outline-success" asp-route-id="@item.Id"><i class="fas fa-edit"></i> Edit</a>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
</div>